services:
  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - desafio_data:/var/lib/postgresql/data

  db_test: 
    image: postgres:17
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER_TEST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}
      - POSTGRES_DB=${POSTGRES_DB_TEST}
    ports:
      - '5433:5432'
    volumes:
      - test_data:/var/lib/postgresql/data

volumes:
  desafio_data:
  test_data:
